# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

p1 = Player.create!(first_name: "Mathieu", last_name: "Debuchy")

p2 = Player.create!(first_name:"Kieran", last_name:"Gibbs")

p3 = Player.create!(first_name:"Nacho", last_name: "Monreal")


  g1 = p1.games.create!(goals: "2",
    assists: "2",
    clean_sheets: "2",
    appearances: "2",
    total_shots: "2",
    shots_on_target: "2",
    shots_in_box: "2",
    shots_outside_box: "2",
    ariel_duels: "2",
    successful_take_on: "2",
    goal_conversion_rate: "2",
    total_passes: "2",
    forward_passes: "2",
    backward_passes: "2",
    successful_passes: "2",
    chances_created: "2",
    key_passes: "2",
    long_balls: "2",
    cross_accuracy: "2",
    total_tackles: "2",
    tackles_won: "2",
    def_aerial_duels: "2",
    blocks: "2",
    fouls_committed: "2",
    tackles_lost: "2",
    defensive_errors: "2",
    clearances: "2",
    distribution_accuracy: "2",
    punches: "2",
    catches: "2",
    dropped_ball_from_catch: "2",
    # total: MyString,
    _saves: "2",
    saves_with_feet: "2",
    saves_bottom_corners: "2",
    saves_top_corners: "2",
    yellow_card: "2",
    red_card: "2",
    cards_diving: "2",
    # cards_: MyString,
    bad_tackle: "2")

    g1 = p3.games.create!(goals: "4",
      assists: "4",
      clean_sheets: "4",
      appearances: "4",
      total_shots: "4",
      shots_on_target: "4",
      shots_in_box: "4",
      shots_outside_box: "4",
      ariel_duels: "4",
      successful_take_on: "4",
      goal_conversion_rate: "4",
      total_passes: "4",
      forward_passes: "4",
      backward_passes: "4",
      successful_passes: "4",
      chances_created: "4",
      key_passes: "4",
      long_balls: "4",
      cross_accuracy: "4",
      total_tackles: "4",
      tackles_won: "4",
      def_aerial_duels: "4",
      blocks: "4",
      fouls_committed: "4",
      tackles_lost: "4",
      defensive_errors: "4",
      clearances: "4",
      distribution_accuracy: "4",
      punches: "4",
      catches: "4",
      dropped_ball_from_catch: "4",
      # total: MyString,
      _saves: "4",
      saves_with_feet: "4",
      saves_bottom_corners: "4",
      saves_top_corners: "4",
      yellow_card: "4",
      red_card: "4",
      cards_diving: "4",
      # cards_: MyString,
      bad_tackle: "4")
